services:
  - type: worker
    name: telegram-checkin-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: TOKEN
        sync: false
    secretFiles:
      - name: credentials.json
        mountPath: /etc/secrets/credentials.json
