services:
  - type: worker         # не web, а background worker
    name: telegram-checkin-bot
    env: python          # ключевой момент!
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: TOKEN
        sync: false
    secretFiles:
      - name: credentials.json
        mountPath: /etc/secrets/credentials.json
