services:
  - type: web         # или worker, если не нужен HTTP-порт
    name: telegram-checkin-bot
    env: python
    runtime: python3.10
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: TOKEN
        sync: false
    secretFiles:
      - name: credentials.json
        mountPath: /etc/secrets/credentials.json
