services:
  - type: worker
    name: telegram-checkin-bot
    env: python
    # Устанавливаем зависимости
    buildCommand: pip3 install -r requirements.txt
    # Запускаем скрипт через python3
    startCommand: python3 bot.py
    secretFiles:
      - name: credentials.json
        mountPath: /etc/secrets/credentials.json
    envVars:
      - key: TOKEN
        sync: false
